---
- hosts: ip-172-31-69-236.ec2.internal
  become: true
  tasks:

   - name: Run the equivalent of "apt-get update" as a separate step
     ansible.builtin.apt:
       update_cache: yes

   - name: Install apache httpd  (state=present is optional)
     ansible.builtin.apt:
       name: apache2
       state: present

   - name: Start service apache2, if not started
     ansible.builtin.service:
       name: apache2
       state: started

   - name: Copy file with owner and permissions
     ansible.builtin.copy:
       src: index.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: '0644'
