apiVersion: v1
kind: ReplicationController
metadata:
  name: todo-deploy
spec:
  replicas: 2
  selector:
    app: todo
  template:
    metadata:
      name: todo
      labels:
        app: todo
    spec:
      containers:
      - name: todo-container
        image: anilbidari/todo:1.0
        ports:
        - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: todo-lb
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: todo
  type: LoadBalancer
